#!/bin/sh
#Taken from D.Buenzli, https://github.com/dbuenzli/uutf/blob/master/build.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
        default) $OCAMLBUILD src/tiger2ml.native ;;
        clean)   $OCAMLBUILD -clean ;;
        *)       $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
